# Generated by Django 5.0.6 on 2024-06-09 09:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Эл. почта')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house', models.CharField(max_length=100, verbose_name='№ дома')),
                ('levels', models.IntegerField(choices=[('FACTORY', 0), ('RETAIL_NETWORK', 1), ('IP', 2)], default=('FACTORY', 0), verbose_name='Уровень структуры')),
                ('debt', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Задолженность')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Уровень поставки',
                'verbose_name_plural': 'Уровни поставки',
            },
        ),
    ]
